### PR TITLE
add SOLR schema textgen searchable fields for identifiedBy and recordedBy

### PR DESCRIPTION
**Pull request by adam-collins**

### CODE REVIEW

**Review by brucehyslop — APPROVED** [review]

**Comment by djtfmartin** [comment]
Can we chose a naming convention that isn't so tied to a specific field type in SOLR?

**Review by djtfmartin — CHANGES_REQUESTED** [review]
Can we choose a naming convention that isn't so tied to a specific field type in SOLR?

**Comment by brucehyslop** [comment]
Is there a reason why we couldn't change the type of the fields `recordedBy` and `identifiedBy` from `text` to `textgen`? 

Would this have a detrimental effect when searching on these fields?

**Comment by djtfmartin** [comment]
Closing this PR after discussion with @adam-collins 

We've renamed the fields to `text_recordedBy` and `text_identifiedBy` but keeping textgen field type.

Changes added to this PR: https://github.com/gbif/pipelines/pull/528

**Pull request closed without merging**
