### PR TITLE
Having these fields as text will allow to perform partial against them

### PR DESCRIPTION
**Pull request by fmendezh**
Changing these fields to be text will allow performing partial search matches against their values.
Be aware that this will require to change all mappings of those fields to be fieldName.keyword to preserve the current behavior (see https://github.com/gbif/occurrence/blob/master/occurrence-search/src/main/java/org/gbif/occurrence/search/es/OccurrenceEsField.java#L64)

https://github.com/gbif/pipelines/issues/253
https://github.com/gbif/occurrence/issues/39

### CODE REVIEW

**Comment by MattBlissett** [comment]
Is there a way to fix https://github.com/gbif/portal-feedback/issues/2887 too?

(NB merge is currently to master. "Edit" looks like it can change that.)

**Comment by fmendezh** [comment]
> Is there a way to fix [gbif/portal-feedback#2887](https://github.com/gbif/portal-feedback/issues/2887) too?
> 
> (NB merge is currently to master. "Edit" looks like it can change that.)
@MattBlissett  We can remove the lowercase_normalizer but we must be aware that all queries and facets will become case sensitive::

1.  A query like recordedBy=Matt it will be different to recorededBy=MATT
2.  Facets response can have now:  Matt: 100, and MATT:300  (which I think is what Niki wants)

**Comment by muttcg** [comment]
Are you sure about occurrenceId, catalogNumber, and other identifiers?

**Comment by timrobertson100** [comment]
It is common that people have e.g. "123 Robertson" for a field number, so it would be useful to have this tokenised search on occurrenceId, recordNumber, fieldNumber, catalogNumber and otherCatalogNumbers (which is often delimited in other ways=

**Comment by muttcg** [comment]
> It is common that people have e.g. "123 Robertson" for a field number, so it would be useful to have this tokenised search on occurrenceId, recordNumber, fieldNumber, catalogNumber and otherCatalogNumbers (which is often delimited in other ways=

I see, thanks

@fmendezh Can we merge it into dev branch, instead of master? We will have to recreate the index with these changes, at the same time new features in dev require full reindexing

**Comment by MattBlissett** [comment]
Changing the base branch on Github seems to have worked, it's now ready to merge into gbif-dev.

**Pull request merged**
