### PR TITLE
Remove hardcoded hdfs prefix

### PR DESCRIPTION
**Pull request by muttcg**
@djtfmartin your latest changes broke our ingestion, I fixed it and removed hardcoded hdfs prefix everywhere, the fix should work with your code without any changes, please review changes

### CODE REVIEW

**Comment by djtfmartin** [comment]
@muttcg can you share examples of `core-site.xml` and `hdfs-site.xml` ?

**Comment by timrobertson100** [comment]
> @muttcg can you share examples of `core-site.xml` and `hdfs-site.xml` ?

I've done this in private comms

**Comment by djtfmartin** [comment]
thanks @timrobertson100 

The supplied XML docs are big - i guess the better question is what are mandatory params in each ?
i.e. what was missing that broke things in your environment that other users should be aware of...

**Comment by muttcg** [comment]
> thanks @timrobertson100
> 
> The supplied XML docs are big - i guess the better question is what are mandatory params in each ?
> i.e. what was missing that broke things in your environment that other users should be aware of...

hdfsSiteConfig returns some default FS when you do config.get("fs.default.name"), while value in xml doesn't exist
but in our case coreSiteConfig contains "fs.default.name", core-site.xml and hdfs-site.xml are generated by Cloudera

**Comment by djtfmartin** [comment]
I think ive answered my own question - i can see the code is now checking for `fs.defaultFS` in both hdfs-site.xml and core-site.xml

**Pull request merged**
