### PR TITLE
Interpret point footprints and assume WGS84 for footprints if unspecified

### PR DESCRIPTION
**Pull request by MattBlissett**
#509 — issues for footprintWKT:

Two things are fixed:
1. Interpretation of `POINT(lng lat)` footprints
2. Interpretation of footprints without a dwc:footprintSRS, which was failing.

### CODE REVIEW

**Comment by MattBlissett** [comment]
@fmendezh, I hadn't realized this wasn't merged.  It's for #509, and we have millions of affected occurrences.

**Comment by MattBlissett** [comment]
Could this be reviewed and merged @fmendezh / @muttcg? I have rebased it onto dev.

**Comment by muttcg** [comment]
@MattBlissett Do you want to release it after? Dev got many changes and if you want to release the feature, then better to use Master.

**Comment by MattBlissett** [comment]
I'm not in a hurry, I just found it when I was looking through old issues.  Dev or master, whichever suits you.

**Review by muttcg — APPROVED** [review]

**Pull request merged**
